# Generated by Django 4.1.3 on 2022-11-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="photo",
            field=models.URLField(null=True),
        ),
    ]
