# Generated by Django 4.1.3 on 2022-11-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_location_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="photo",
            new_name="picture_url",
        ),
    ]
